### PR TITLE
Issue 6

### LINKED ISSUE #6: The pod has a folder that doesn't compile on a non-UNIX system
In this directory: `Marshroute/Marshroute/Sources/Transitions/TransitionAnimations/Navigation/`, there's a folder called `Push/Pop`. Cloning a repository on a Windows system (for example) that has this cocoapod, makes the git checkout not work. It complains that the folder `Push:Pop` is an invalid argument.

### PR DESCRIPTION
**Pull request by Usipov**
To fix #6

### CODE REVIEW

**Review by ignatovv — APPROVED** [review]

**Review by vkaltyrin — APPROVED** [review]

File: Example/NavigationDemo/VIPER/Application/View/ApplicationViewController.swift [hunk 1]
```diff
@@ -40,7 +40,7 @@ final class ApplicationViewController: BaseTabBarController, ApplicationViewInpu
             x: 0,
             y: 0,
             width: containerViewController.view.frame.width,
-            height: topViewController.topLayoutGuide.length ?? 44
+            height: topViewController.topLayoutGuide.length
```
Comment (Usipov) [inline Example/NavigationDemo/VIPER/Application/View/ApplicationViewController.swift:43]: Fixed a warning in a demo project
Nothing serious

**Review by west0r — APPROVED** [review]
